# Generated by Django 2.2.12 on 2020-11-30 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='Telefon Numarası')),
                ('gender', models.CharField(choices=[('', 'Cinsiyet Seçiniz'), ('Kadın', 'Kadın'), ('Erkek', 'Erkek')], max_length=20, verbose_name='Cinsiyet')),
                ('Adres', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
