# Generated by Django 2.2.12 on 2020-11-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Başlık')),
                ('description', models.CharField(max_length=120, verbose_name='İçerik')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='YayınlanmaTarihi')),
                ('urun_adedi', models.IntegerField(default=100)),
                ('pre_fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Önceki Fiyat')),
                ('fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image', models.ImageField(upload_to='', verbose_name='Ana Resim')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='İkinci Resim')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Üçüncü Resim')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Dördüncü Resim')),
                ('category', models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Sweatshirt', 'Sweatshirt'), ('Kapisonlu', 'Kapisonlu'), ('Aksesuar', 'Aksesuar'), ('Esofman', 'Esofman')], max_length=15)),
                ('slug', models.SlugField(editable=False, max_length=140, unique=True)),
            ],
            options={
                'ordering': ['-publishing_date'],
            },
        ),
    ]
