# Generated by Django 2.2.12 on 2020-11-30 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tshirt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=9, verbose_name='Sipariş Kodu')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(max_length=15, null=True, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=20, null=True, verbose_name='Soyad')),
                ('phone', models.CharField(max_length=11, verbose_name='Telefon Numarası')),
                ('address', models.CharField(max_length=150, verbose_name='Adres')),
                ('city', models.CharField(max_length=28, verbose_name='Şehir')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Toplam Tutar')),
                ('status', models.CharField(choices=[('Yeni', 'Yeni'), ('Kabul Edildi', 'Kabul Edildi'), ('Hazırlanıyor', 'Hazırlanıyor'), ('Sipariş Kargoya Verildi', 'Sipariş Kargoya Verildi'), ('Sipariş Tamamlandı', 'Sipariş Tamamlandı'), ('İptal Edildi', 'İptal Edildi')], default='Yeni', max_length=12, verbose_name='Sipariş Durumu')),
                ('sozlesme', models.BooleanField(default=True, verbose_name='Mesafeli Satış Sözleşmesi & Şartlar Ve Koşulları Okudum ve Onaylıyorum')),
                ('ip', models.CharField(blank=True, max_length=28)),
                ('adminnote', models.CharField(blank=True, max_length=100, verbose_name='Yönetici Notu')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('odeme', models.BooleanField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('beden', models.CharField(choices=[('', 'Beden Seçiniz.'), ('S-M', 'S-M'), ('L-XL', 'L-XL'), ('Varsayılan', 'Varsayılan')], max_length=10)),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tshirt.Item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('beden', models.CharField(max_length=12)),
                ('fiyat', models.FloatField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], default='New', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tshirt.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
